I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/tl/russian/screens.rpy", line 82, in script
    old "{#auto_page}A"
Exception: A translation for "{#auto_page}A" already exists at game/tl/russian/screens.rpy:79.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/tl/russian/screens.rpy", line 82, in script
    old "{#auto_page}A"
  File "C:\Users\levka\Documents\renpy-8.2.3-sdk\renpy\ast.py", line 2633, in execute
    renpy.translation.add_string_translation(self.language, self.old, self.new, newloc)
  File "C:\Users\levka\Documents\renpy-8.2.3-sdk\renpy\translation\__init__.py", line 556, in add_string_translation
    stl.add(old, new, newloc)
  File "C:\Users\levka\Documents\renpy-8.2.3-sdk\renpy\translation\__init__.py", line 496, in add
    raise Exception("A translation for \"{}\" already exists at {}:{}.".format(
Exception: A translation for "{#auto_page}A" already exists at game/tl/russian/screens.rpy:79.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.3.24061702
bunbun alpha 1.0
Fri Jul 19 22:55:54 2024
